apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: forgery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgery-backend
  template:
    metadata:
      labels:
        app: forgery-backend
    spec:
      containers:
      - name: backend
        image: forgery-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"